title: MishaNya
description: Full-Stack Developer | Go, Python, Microservices, and AI-Powered Solutions.
baseurl: "" # e.g. "/portfolio" if using project pages
url: "https://MishaNyaCopilot.github.io" # replace with your username
theme: null
markdown: kramdown
kramdown:
  input: GFM

collections:
  projects:
    output: true
    permalink: /projects/:slug/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project

nav:
  - name: Home
    url: /
  - name: Projects
    url: /projects/
  - name: About
    url: /about/

social:
  telegram: MishaNyaIsTaken

plugins: []