title: MishaNya
description: Software Engineer | Python Specialist | Building Scalable Backends, Mobile Apps & AI-Powered Solutions.
baseurl: ""
url: "https://MishaNyaCopilot.github.io"
theme: null
markdown: kramdown
kramdown:
  input: GFM

collections:
  projects:
    output: true
    permalink: /projects/:slug/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project

nav:
  - name: Home
    url: /
  - name: Projects
    url: /projects/
  - name: About
    url: /about/

social:
  telegram: MishaNyaIsTaken

plugins: []